version: '3.8'
services:
  db:
    image: postgres:16.6
    container_name: goethe_hub_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:7.2-alpine
    container_name: goethe_hub_redis
    restart: always
    read_only: true
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true