CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO roles (id, codename, created_at, updated_at)
VALUES
  (uuid_generate_v4(), 'ADMINISTRATOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4(), 'TEACHER_MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4(), 'TEACHER_STAFF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4(), 'STUDENT_FREE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4(), 'STUDENT_PAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);